apiVersion: v1
kind: ServiceAccount
metadata:
  name: kubesight
  labels:
    app.kubernetes.io/component: kubesight
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: kubesight
  labels:
    app.kubernetes.io/component: kubesight
rules:
  - apiGroups: ["extensions", "apps"]
    resources: ["deployments"]
    verbs: ["get", "list", "watch"]
  - apiGroups: [""]
    resources: ["pods"]
    verbs: ["get", "list", "watch"]
  - apiGroups: [""]
    resources: ["pods/log"]
    verbs: ["get", "list", "watch"]
  - apiGroups: [""]
    resources: ["secrets"]
    verbs: ["get"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: kubesight
  labels:
    app.kubernetes.io/component: kubesight
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: kubesight
subjects:
  - kind: ServiceAccount
    name: kubesight
